# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hi, I'm darkprotocol9
tagline: darkprotocol9
description: >-
  ... and this is my weblog.
baseurl: "" # the subpath of your site, e.g. /blog
url:     "https://darkprotocol9.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:year/:title/
github_username:  darkprotocol9
email:
title_image: https://scontent-lga3-2.cdninstagram.com/v/t51.2885-19/465486235_1478498262839921_3726442401525232095_n.jpg

# Build settings
markdown: kramdown
# theme: jekyll-theme-hydeout # avoid github pages warnings
remote_theme: fongandrew/hydeout
highlighter: rouge
syntax_theme: monokai
paginate: 10
plugins:
  - jekyll-feed
  - jekyll-redirect-from
feed:
  categories:
    - carnet
    - code
    - talks
author:
  name: Dark Protocol9
jekyll_tidy:
  # exclude: [ "*.md" ]
  compress_html: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
